#!/bin/bash

# Pull Chat API from Docker Hub
# Generated by push-to-dockerhub.sh

set -e

echo "🐳 Pulling Chat API from Docker Hub..."

# Pull the image
docker pull ysscott2012/interview-chat-api:latest

echo "✅ Image pulled successfully!"
echo ""
echo "🚀 To run the container:"
echo "   docker run -d --name chat-api -p 3000:3000 ysscott2012/interview-chat-api:latest"
echo ""
echo "📖 API Documentation:"
echo "   http://localhost:3000/api-docs"
echo "   http://localhost:3000/health"
